mysite/courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('<int:course_id>/', views.detail, name= 'detail'),
    path('<int:course_id>/results', views.results, name= 'results'),
    path('<int:course_id>/vote', views.vote, name= 'vote'),
    path('form/', views.get_name, name= 'form'),
    path('', views.home, name= 'home'),
    path('courses/', views.get_courses, name= 'courses'),
    path('show-course/<int:course_id>/', views.show_course, name= 'show_course'),
    path('create-attendee/<int:course_id>/', views.create_attendee, name= 'create_attendee'),
    path('areyousure/<int:course_id>/', views.areyousure, name= 'areyousure'),
    path('delete-course/<int:course_id>/', views.delete_course, name= 'delete_course'),
    path('delete-attendee/<int:attendee_id>/', views.delete_attendee, name= 'delete_attendee'),
    path('update-attendee/<int:attendee_id>/<int:course_id>', views.update_attendee, name= 'update_attendee'),
]

mysite/emailer/urls.py
from django.urls import path


from . import views

app_name = 'emailer'
urlpatterns = [
    path('', views.show_emails, name='show_emails'),
    path('add-message/', views.add_message, name='add_message'),
    path('conduct-quiz/<int:quiz_id>', views.conduct_quiz, name='conduct_quiz'),
    path('scores/<int:quiz_id>', views.score, name='score'),
    path('start/', views.start, name='start'),
    path('create-quiz/', views.create_quiz, name='create_quiz'),
    path('delete-quiz/<int:quiz_id>', views.delete_quiz, name='delete_quiz'),
] 

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('courses/', include('courses.urls')),
    path('emailer/', include('emailer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('yaratici.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),

] 

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;500;800;900&family=Open+Sans:wght@300;400;700&display=swap"rel="stylesheet">
    <script src="https://kit.fontawesome.com/8ca48c6d4e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'courses/css/style.css' %}">
    <title>ED's</title>
</head>

<body>

{% include "./header.html" %}

<div class="container mt-3">

{% block content %}
{% endblock  %}

</div>

{% include "./footer.html" %}

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>

</html>

mysite/templates/footer.html
  <!-- Footer -->
  <footer>
    <div class="container pt-5">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span  class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span  class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span  class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted text-center">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

mysite/templates/header.html
<!-- Header -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'courses:home' %}">E.D.'s</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:home' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:courses' %}">Course App</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'emailer:start' %}">Quiz App</a>
                </li>
                {%if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Register</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}