mysite/courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('<int:course_id>/', views.detail, name= 'detail'),
    path('<int:course_id>/results', views.results, name= 'results'),
    path('<int:course_id>/vote', views.vote, name= 'vote'),
    path('form/', views.get_name, name= 'form'),
    path('', views.home, name= 'home'),
    path('courses/', views.get_courses, name= 'courses'),
    path('show-course/<int:course_id>/', views.show_course, name= 'show_course'),
    path('create-attendee/<int:course_id>/', views.create_attendee, name= 'create_attendee'),
    path('areyousure/<int:course_id>/', views.areyousure, name= 'areyousure'),
    path('delete-course/<int:course_id>/', views.delete_course, name= 'delete_course'),
    path('delete-attendee/<int:attendee_id>/', views.delete_attendee, name= 'delete_attendee'),
    path('update-attendee/<int:attendee_id>/<int:course_id>', views.update_attendee, name= 'update_attendee'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('courses/', include('courses.urls')),
    path('emailer/', include('emailer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('yaratici.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),

] 

mysite/courses/models.py
from django.db import models

# Create your models here.

from django.db import models
import datetime
from django.utils import timezone


class Course(models.Model):
    course_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.course_name

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Attendee(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.name

mysite/courses/forms.py
from django import forms
from .models import Course

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)


class CourseForm(forms.Form):
    course_name = forms.CharField(max_length=100)
    pub_date = forms.DateTimeField()


class AttendeeForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Course.objects.all())
    name = forms.CharField(max_length=100)
    email = forms.CharField(max_length=200)
    votes = forms.IntegerField()

mysite/courses/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, Http404, HttpResponseRedirect, request
from .models import Course, Attendee
from django.shortcuts import render
from django.urls import reverse
from .forms import AttendeeForm, ContactForm, CourseForm
from django.core.mail import send_mail, EmailMultiAlternatives
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
import random
import requests
import os

# GET quotes


def get_quote():
    data = requests.get('https://type.fit/api/quotes')
    data.raise_for_status()
    data = data.json()
    random_nr = random.randint(0, len(data))
    # email_sender()
    return data[random_nr]

def email_sender():
        # email template finder
    module_dir = os.path.dirname(__file__)  
    file_path = os.path.join(module_dir, '../templates/email.html')   #full path to text.
    with open(file_path, encoding='utf8') as file:
        data = file.read()
        # print(data)
    # email class
        subject, from_email, to = 'Html test', settings.EMAIL_HOST_USER, 'berdushwile@gmail.com'
        text_content = 'This is an important message.'
        html_content = data

        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()



def home(request):
    return render(request, template_name='courses/landing-page.html', context={'quote': get_quote()})


def index(request):
    course_list = Course.objects.order_by('pub_date')
    context = {
        'course_list': course_list,
    }
    return render(request, 'courses/index.html', context)


def detail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    # print(course.attendee_set.all())
    return render(request, 'courses/detail.html', context={'course': course})


def results(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'courses/results.html', {'course': course})


def vote(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    print(request.POST['choice'])
    selected_attendee = course.attendee_set.get(pk=request.POST['choice'])
    selected_attendee.votes += 1
    selected_attendee.save()
    return HttpResponseRedirect(reverse('courses:results', args=(course_id,)))


def get_name(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['info@example.com']
            if cc_myself:
                recipients.append(sender)

            send_mail(subject, message, sender, recipients)
    else:
        form = ContactForm()
    return render(request, 'courses/name.html', {'form': form})

# MainPage


def get_courses(request):
    courses = Course.objects.all()
    form = CourseForm()
    # Create New Course
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            new_course = Course(
                course_name=form.cleaned_data['course_name'], pub_date=form.cleaned_data['pub_date'])
            new_course.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Course Successfully Saved')
            return HttpResponseRedirect(reverse('courses:courses'))
    return render(request, template_name='courses/courses.html', context={'courses': courses, 'form': form})

# Edit Course


def show_course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    form = CourseForm({'course_name': course.course_name,
                       'pub_date': course.pub_date})
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            course.course_name = form.cleaned_data['course_name']
            course.pub_date = form.cleaned_data['pub_date']
            course.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Course Successfully Updated')
            return HttpResponseRedirect(reverse('courses:courses'))
    return render(request, template_name='courses/show-course.html', context={'course': course, 'form': form})

# Create Attendee


def create_attendee(request, course_id):

    form2 = AttendeeForm({'course': Course.objects.get(pk=course_id)})

    if request.method == 'POST':
        form2 = AttendeeForm(request.POST)
        if form2.is_valid():
            print(form2.cleaned_data['course'])
            new_attendee = Attendee(
                course=form2.cleaned_data['course'],
                name=form2.cleaned_data['name'],
                email=form2.cleaned_data['email'],
                votes=int(form2.cleaned_data['votes'])
            )
            new_attendee.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Successfully Added new Attendee')
            return HttpResponseRedirect(reverse('courses:courses'))
    return render(request, template_name='courses/create-attendee.html', context={'form2': form2, 'course_id': course_id})

# Are You Sure?


def areyousure(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, template_name='courses/areyousure.html', context={'course': course})


# Delete Course
def delete_course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    course.delete()
    messages.add_message(request, messages.SUCCESS,
                         'Course Successfully Deleted')
    return HttpResponseRedirect(reverse('courses:courses'))

# Update Attendee


def update_attendee(request, attendee_id, course_id):
    attendee = get_object_or_404(Attendee, pk=attendee_id)
    course = get_object_or_404(Course, pk=course_id)
    form = AttendeeForm({
        'course': course,
        'name': attendee.name,
        'email': attendee.email,
        'votes': attendee.votes,
    })
    if request.method == 'POST':
        form = AttendeeForm(request.POST)
        if form.is_valid():
            attendee.course = form.cleaned_data['course']
            attendee.name = form.cleaned_data['name']
            attendee.email = form.cleaned_data['email']
            attendee.votes = form.cleaned_data['votes']
            attendee.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Attendee Successfully Updated')
        return HttpResponseRedirect(reverse('courses:courses'))
    return render(request, template_name='courses/update-attendee.html', context={'attendee': attendee, 'form': form})


# Delete Attendee
def delete_attendee(request, attendee_id):
    attendee = get_object_or_404(Attendee, pk=attendee_id)
    attendee.delete()
    messages.add_message(request, messages.SUCCESS,
                         'Attendee Successfully Deleted')
    return HttpResponseRedirect(reverse('courses:courses'))

mysite/templates/courses/areyousure.html
{% extends '../base.html' %}

{% block content %}

<div class="container">
    <div class="card w-50 mx-auto mt-5 text-center text-white bg-dark">
      <div class="card-header">
        Action Required
      </div>
      <div class="card-body bg-secondary">
        <h5 class="card-title">Are you sure do you want to delete?</h5>
        <h4><p class="card-text">Course: {{course.course_name}} <br> Date: {{course.pub_date|date}}</p></h4>
        <a href="{% url 'courses:courses' %}" class="btn btn-warning mr-3">Go Back</a>
          <a href="{% url 'courses:delete_course' course.id %}" class="btn btn-danger">Confirm</a>
      </div>
    </div>
    </div>

{% endblock %}

mysite/templates/courses/courses.html
{% extends '../base.html' %}


{% block content %}
<!--Course Details-->


<div class="row">
    <div class="col-lg-12 mx-auto">
        <h1>Registered Courses
            <a href="#"><button type="button" class="btn btn-success "> </button></a>

        </h1>
        <!--Registered Courses-->
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Ders</th>
                    <th scope="col">Tarih</th>
                    <th scope="col">Attendees</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}

                <tr>
                    <a href="{% url 'courses:show_course' course.id %}"></a>
                    <td>
                        <p style="margin:0px">{{ course.course_name }}</p>
                    </td>

                    <td>
                        <p style="margin:0px">{{ course.pub_date | date:"D d M Y" }}</p>
                    </td>
                    <td>
                        <p style="margin:0px">{{course.attendee_set.all.count}}</p>
                    </td>
                    <td>

                        <a href="{% url 'courses:show_course' course.id %}"><button type="button"
                                class="btn btn-warning btn-sm">Show <i class="fas fa-address-book"></i></button></a>
                        <a href="{% url 'courses:areyousure' course.id %}"><button type="button"
                                class="btn btn-danger btn-sm">Delete <i class="fas fa-trash-alt"></i></button></a>
                        <a href="#"><button type="button" class="btn btn-outline-primary btn-sm">Email <i
                                    class="fas fa-envelope-open"></i></button></a>
                        <a href="{% url 'courses:create_attendee' course.id %}"><button type="button"
                                class="btn btn-info btn-sm">Add User <i class="fas fa-user"></i></button></a>
                    </td>

                    {% endfor %}
                </tr>
        </table>
    </div>
    <hr>

    <div class="col-lg-12">
        <hr>
        <h2>Create New Course</h2>
        <h6>
            <form action="{% url 'courses:courses'%}" method="post" class="form-group" novalidate>
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Create New Course">
            </form>
        </h6>
        <br>
    </div>

    {% if request.user.is_authenticated %}
<i style="color:green" class="far fa-handshake"></i>
{% endif %}
    {% endblock %}

mysite/templates/courses/create-attendee.html
{% extends '../base.html' %}

{% block content %}

<h2>Create New Attendee</h2>
            <form action="{% url 'courses:create_attendee' course_id%}" method="post" class="form-group" novalidate>
                {% csrf_token %}
                {{ form2 }}
                <input type="submit" value="Submit">
            </form>

{% endblock %}

mysite/templates/courses/detail.html
<h1>{{ course.course_name }}</h1>


<form action="{% url 'courses:vote' course.id %}" method="post">
    {% csrf_token %}
    {% for choice in course.attendee_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.name }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
<br>

mysite/templates/courses/index.html
{% extends './base.html' %}


{% block content %}

{% if course_list %}
<ul>
    {% for course in course_list %}
    <li><a href="{% url 'courses:detail' course.id %}">{{ course.course_name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}


<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto py-5">
            {% for course in course_list %}
            <div class="post-preview">
                <a href="{% url 'courses:detail' course.id %}">
                    <h2 class="post-title">
                        {{course.course_name}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{course.pub_date}}
                    </h3>
                </a>
                <p class="post-meta">Posted by
                    {{course.id}}
                    add X for admin delete
                    
                </p>
            </div>
            <hr>
            {% endfor %}


            <!-- New Post -->

            <div class="clearfix">
                <a class="btn btn-primary float-right" href="#">Create New Post</a>
            </div>

        </div>
    </div>
</div>

{% endblock  %}

mysite/templates/courses/name.html
<form action="{% url 'courses:form'%}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

mysite/templates/courses/results.html
<h1>{{course.course_name}}</h1>

{% for attendee in course.attendee_set.all %}
<li><a href="{% url 'courses:detail' course.id %}">{{ attendee.name }}- {{attendee.votes}}</a></li>
{% endfor %}

mysite/templates/courses/show-course.html
{% extends '../base.html' %}


{% block content %}

<!--Course Details-->
<div class="container mt-3">
    <div class="row">
        <div class="col-lg-12 mx-auto ">
            <h1>Course: {{course.course_name}} - Date: {{course.pub_date|date}} Details
                <a href="{% url 'courses:courses' %}"><button type="button" class="btn btn-success ">Go Back </button></a>
            </h1>

            <!--Registered Attendees-->
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">İsim</th>
                        <th scope="col">Email</th>
                        <th scope="col">Course</th>
                        <th scope="col">Votes</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {%for attendee in course.attendee_set.all %}
                    <tr>
                        <td>
                            <p style="margin:0px">{{ attendee.name }}</p>
                        </td>
                        <td>
                            <p style="margin:0px">{{ attendee.email }}</p>
                        </td>
                        <td>
                            <p style="margin:0px">{{ course.course_name}}-{{ course.pub_date|date}}</p>
                        </td>
                        <td>
                            <p style="margin:0px">{{ attendee.votes}}</p>
                        </td>
                        <td>
                            <a href="{% url 'courses:update_attendee' attendee.id course.id %}"><button type="button"
                                    class="btn btn-warning btn-sm">Edit <i class="fas fa-user-edit"></i></button></a>
                            <a href="{% url 'courses:delete_attendee' attendee.id %}"><button type="button" class="btn btn-danger btn-sm">Delete <i
                                        class="fas fa-trash-alt"></i></button></a>
                            <a href="#"><button type="button" class="btn btn-outline-primary btn-sm">Email <i
                                        class="fas fa-envelope-open"></i></button></a>
                        </td>
                    </tr>
                    {%endfor %}
            </table>
        </div>
    </div>
    <hr>
    

    <div class="container mx-auto">
        <h4 class="text-center"> Edit Course Date and Time </h4>
            <h6 class="text-center"><form action="{% url 'courses:show_course' course.id %}" method="post" novalidate>
                {% csrf_token %}
                {{ form}}
                <input type="submit" value="Update Course">
            </form>
        </h6>
        <hr>
        
    </div>

    {% endblock %}

mysite/templates/courses/update-attendee.html
{% extends '../base.html' %}

{% block content %}



<form action="" method="post" class="form-group" novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Update Attendee">
</form>


{% endblock %}