mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('courses/', include('courses.urls')),
    path('emailer/', include('emailer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('yaratici.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),

] 

mysite/yaratici/urls.py
from django.urls import path
from . import views

app_name = 'yaratici'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('home', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('question/', views.get_question, name='get_question'),
    path('results/<int:question_id>', views.question_results, name='question_results'),
    path('post/<slug:slug>', views.show_post, name='show_post'),
    # path('add-message/', views.add_message, name='add_message'),
    # path('conduct-quiz/<int:quiz_id>', views.conduct_quiz, name='conduct_quiz'),
    # path('scores/<int:quiz_id>', views.score, name='score'),
    # path('start/', views.start, name='start'),
    # path('create-quiz/', views.create_quiz, name='create_quiz'),
    # path('delete-quiz/<int:quiz_id>', views.delete_quiz, name='delete_quiz'),
] 

mysite/yaratici/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField


# Create your models here.

class BlogPost(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE )
    title = models.CharField(max_length=255)
    meta_title = models.CharField(max_length=255)
    meta_tags = models.CharField(max_length=255,blank=True)
    photo = models.ImageField(upload_to='blog_img')
    create_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)
    is_Published = models.BooleanField(default=False)
    message = RichTextField(blank=True,null=True)
    slug = models.SlugField()

    def __str__(self):
            return self.title

    def get_absolute_url(self):
        return reverse('yaratici:show_post', kwargs={'slug':self.slug})


from datetime import timedelta 



class Question(models.Model):
    question = models.CharField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    is_Published = models.BooleanField(default=False)
    publish_date = models.DateTimeField()
    
    def __str__(self):
        return self.question


class Choices(models.Model):
    question = models.ForeignKey('Question',on_delete=models.CASCADE)
    choice = models.CharField(max_length = 250)
    counter = models.IntegerField(default=0)

    def __str__(self):
        return self.choice

mysite/yaratici/forms.py
from django.forms import ModelForm
from .models import Choices
from django import forms



class ChoiceForm(ModelForm):
    class Meta:
        model = Choices
        fields = ['choice']

mysite/yaratici/views.py
from .models import BlogPost, Question,Choices
from .forms import ChoiceForm
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.urls import reverse

# Create your views here.


def landing_page(request):
    return render(request, 'yaratici/landing.html')


def home(request):
    posts = BlogPost.objects.order_by('-create_date')[:3]
    print(posts)
    kimim = BlogPost.objects.get(slug__iexact="ben-kimim")
    return render(request, 'yaratici/home.html', {'kimim': kimim, 'posts': posts})


def posts(request):
    posts = BlogPost.objects.all().exclude(id=1).order_by('-create_date')
    return render(request, 'yaratici/posts.html', {'posts': posts})


def show_post(request, slug):
    posts = BlogPost.objects.all().exclude(id=1).order_by('-create_date')[:10]
    post = get_object_or_404(BlogPost, slug=slug)
    return render(request, 'yaratici/post.html', {'post': post, 'posts': posts})

def calc_percentage(x,y):
    return x/y*100

def question_results(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    totalvotes = 0
    dict = {}
    
    for choice in question.choices_set.all():
        totalvotes += choice.counter

    for choice in question.choices_set.all():
        perc = int(calc_percentage(choice.counter,totalvotes))
        dict[choice.choice] = perc
    print(dict)
 

    return render(request, 'yaratici/question-results.html', {'question': question, 'dict':dict})


def get_question(request):
    form = ChoiceForm()
    question = get_object_or_404(Question, is_Published=True)

    if request.method == 'POST':
        print(request.POST)
        if 'response' not in request.POST:
            messages.add_message(request, messages.WARNING, 'You Did Not Select Any Answer')
            print('no selection')
        else:
            print(f"selectedchoice: {request.POST['response']}")
            choice_object = get_object_or_404(Choices,choice=request.POST['response'])
            
            choice_object.counter +=1
            print(choice_object.counter)
            choice_object.save()
            
        return redirect('yaratici:question_results', question_id= question.id)

    return render(request, 'yaratici/show-question.html', {'question': question, 'form': form})

mysite/templates/yaratici/header.html
<style>
    .screen-reader-text[href="#page-content"]:focus {
        background-color: #f1f1f1;
        border-radius: 3px;
        box-shadow: 0 0 2px 2px rgba(0, 0, 0, 0.6);
        clip: auto !important;
        clip-path: none;
        color: #21759b;

    }
</style>
<a class="skip-link screen-reader-text" href="#page-content">Skip to content</a>

{%if 'home' in request.path %}
<div id="page-top" class="header-top homepage">
    <div class="navigation-bar homepage">
        {%else%}
        <div id="page-top" class="header-top">
            <div class="navigation-bar coloured-nav" data-sticky='0' data-sticky-mobile='1' data-sticky-to='top'>
               
{%endif%}

        <div class="navigation-wrapper ">
            <div class="row basis-auto">
                <div class="logo_col col-xs col-sm-fit">
                    <a class="text-logo" data-type="group" data-dynamic-mod="true"
                        href="{% url 'yaratici:home' %}">Yaratıcı<span style="font-weight: 300;"
                            class="span12"> Çocuğum</span></a> </div>
                <div class="main_menu_col col-xs">
                    <div id="mainmenu_container" class="row">
                        <ul id="main_menu" class="active-line-bottom main-menu dropdown-menu">
                            <li id="menu-item-13"
                                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-13">
                                <a href="#page-top"
                                    aria-current="page">Home</a></li>
                            <li id="menu-item-130"
                                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-130">
                                <a href="#blog-yazilari-1"
                                    aria-current="page">Blog YAZILARI</a></li>
                            <li id="menu-item-140"
                                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-140">
                                <a href="#ben-kimim" aria-current="page">Ben
                                    Kimim</a></li>
                        </ul>
                    </div> <a href="#" data-component="offcanvas" data-target="#offcanvas-wrapper"
                        data-direction="right" data-width="300px" data-push="false">
                        <div class="bubble"></div>
                        <i class="fa fa-bars"></i>
                    </a>
                    <div id="offcanvas-wrapper" class="hide force-hide  offcanvas-right">
                        <div class="offcanvas-top">
                            <div class="logo-holder">
                                <a class="text-logo" data-type="group" data-dynamic-mod="true"
                                    href="#">Yaratıcı<span
                                        style="font-weight: 300;" class="span12"> Çocuğum</span></a> </div>
                        </div>
                        <div id="offcanvas-menu" class="menu-main-menu-container">
                            <ul id="offcanvas_menu" class="offcanvas_menu">
                                <li
                                    class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-13">
                                    <a href="{% url 'yaratici:home' %}"
                                        aria-current="page">Home</a></li>
                                <li
                                    class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-130">
                                    <a href="{% url 'yaratici:posts' %}"
                                        aria-current="page">Blog YAZILARI</a></li>
                                <li
                                    class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-140">
                                    <a href="{% url 'yaratici:show_post' slug='ben-kimim' %}"
                                        aria-current="page">Ben Kimim</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

mysite/templates/yaratici/home.html
{%extends './base.html'%}
{% block title %} Yaratıcı Çocuğum - Çocuğunuzun Yaratıcı Enerjisine Dokunun! {% endblock  %}
{% block meta %} NLP Uzmanı Eğitimci Anneden, Çocuklarda Yaratıcılık Üzerine Paylaşımlar. Çocuklarımızla Düzenli Zaman Geçirip, Yaratıcılıklarını Artırlamayı Hedefliyoruz {% endblock  %}

{% block css %}{% endblock css %}

{%block content %}


<div id="page" class="site">

    <div class="header-wrapper">
        <div class='header-homepage  color-overlay  header-full-height' style=''>

            <div class="header-description gridContainer content-on-center">
                <div class="row header-description-row middle-sm">
                    <div class="header-content header-content-centered col-md col-xs-12">
                        <div class="align-holder center">
                            <h1 class="hero-title">Yaratıcı Çocuğum</h1>
                            <p class="header-subtitle">Çocuğunuzun Yaratıcı Enerjisine Dokunun</p>
                            <div data-dynamic-mod-container class="header-buttons-wrapper"><a
                                    class="button big color1 round" target="_self"
                                    href="#">Etkinlikler</a><a
                                    class="button big color-white round outline" target="_self"
                                    href="{%url 'yaratici:posts'%}">Blog Yazıları</a></div>
                        </div>
                    </div>
                </div>
            </div>

            <script>
                if (window.mesmerizeSetHeaderTopSpacing) {
                    window.mesmerizeSetHeaderTopSpacing();
                }
            </script>

            <div class="header-separator header-separator-bottom "><svg class="mesmerize" preserveAspectRatio="none"
                    width="1000" height="100" viewBox="0 0 1000 100" xmlns="http://www.w3.org/2000/svg">
                    <desc>Created with Sketch.</desc>
                    <g fill="#000">
                        <path class="svg-white-bg"
                            d="M0 50.582c50.292 15.873 94.979 23.809 134.063 23.809 160.18 0 189.492-54.182 308.938-54.182 119.445 0 181.541 74.304 377.394 74.935 76.087.245 135.955-14.609 179.606-44.563v49.5h-1000v-49.5z" />
                        <path class="svg-white-bg"
                            d="M0 21.652c33.432 32.916 78.986 49.375 136.66 49.375 160.18 0 186.895-61.035 306.34-61.035 117.359-.152 223.758 80.344 376.938 83.09 76.087.245 136.107-21.467 180.063-65.137v72.136h-1000v-78.429z"
                            fill-opacity=".5" />
                        <path class="svg-white-bg"
                            d="M0 1.082c28.932 45 74.518 67.5 136.758 67.5 160.18 0 158.211-67.5 306.707-67.5 128.447 0 255.178 91.772 376.555 89.852 64.97-1.896 124.964-26.374 179.98-73.434v82.582h-1000v-99z"
                            fill-opacity=".3" />
                    </g>
                </svg></div>
            <div class="header-homepage-arrow-c">
                <span class="header-homepage-arrow move-down-bounce"> <i class="fa arrow fa-angle-down"
                        aria-hidden="true"></i>
                </span>
            </div>
        </div>
    </div>

    <div id='page-content' class="page-content">
        <div class="content">
            <div data-label="Ben Kimim" data-id="about--2" data-export-id="about-9" data-category="about"
                class="about-9 content-section content-section-spacing" id="ben-kimim"
                style="background-color: rgb(255, 255, 255); background-image: none;">
                <div class="gridContainer">
                    <div class="row middle-sm text-center">
                        <div class="col-sm-5 space-bottom-xs content-column content-right-sm" data-type="column">
                            <h5 class="">Yaratıcı Çocuğum Nasıl Doğdu</h5>
                            <h2 class=""><span href="{%url 'yaratici:show_post' slug=kimim.slug %}">Ben Kimim?</span></h2>
                            <p class=""><span>Aslında yalnızca sizlerden biriyim!
                                </span>
                                <br>8 yaşındaki oğlunun doğumuyla birlikte anneliği ilk kez deneyimleyen, çocukları
                                çok seven, çalışan bir anne!&nbsp;</p> <a class="button color1"
                                href="{%url 'yaratici:show_post' slug=kimim.slug %}" target="_self"
                                data-cp-link="1" rel="noopener noreferrer">DEVAMINI OKU</a>
                        </div>
                        <div class="col-sm-7 flexbox flexbox middle-xs center-xs space-bottom-xs">
                            <div class="overlay-box flexbox middle-xs center-xs overlay-holder ">
                                <div class="overlay-box-offset offset-background shadow-medium bg-color2 hide-xs">
                                </div> <a data-cp-link="1" href="#"
                                    target="_self" rel="noopener noreferrer"><img class="flexbox shadow-large img1"
                                        src="{{kimim.photo.url}}"
                                        data-size="600x400" alt=""
                                        title="cropped-Yaratici_Cocugum_Anasayfa.jpg"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div data-label="Blog YAZILARI" data-id="latest_news--1" data-export-id="blog-section-mc"
                data-category="latest_news"
                class="blog-section-mc blog-section-standard content-section content-section-spacing"
                id="blog-yazilari-1" style="background-color: rgb(255, 255, 255);">
                <div class="gridContainer">
                    <div class="row">
                        <div data-type="column" class="section-title-col">
                            <h5 class="">Çocuğunuzun Yaratıcı Enerjisine Dokunun!</h5>
                            <h2 class="">Blog Yazıları</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div data-type="row" data-dynamic-columns="handled"
                            data-content-shortcode="mesmerize_latest_news posts=&quot;3&quot;">
                            <div class="row center-sm content-left-sm">
                                <!-- blog start -->
                                {%for post in posts %}
                                <div id="post-{{post.id}}" class="col-sm-6 col-md-4 space-bottom space-bottom-xs">
                                    <div class="post-content card y-move bordered">
                                        <div class="post-thumbnail">
                                            <a href="{%url 'yaratici:show_post' slug=post.slug %}"
                                                class="post-list-item-thumb ">
                                                <img width="626" height="417"
                                                    src="{{post.photo.url}}"
                                                    class="attachment-post-thumbnail size-post-thumbnail wp-post-image"
                                                    alt="" loading="lazy"
                                                    srcset="{{post.photo.url}} 626w, {{post.photo.url}} 300w"
                                                    sizes="(max-width: 626px) 100vw, 626px" /> </a>
                                        </div>
                                        <div class="col-padding col-padding-xs">
                                            <h3 class="post-title space-bottom-small">
                                                <a href="{%url 'yaratici:show_post' slug=post.slug %}"
                                                    rel="bookmark">
                                                    {{post.title}} </a>
                                            </h3>
                                            <p>{{post.message|slice:':300'|safe}}</p>
                                            <a class="read-more link"
                                                href="{%url 'yaratici:show_post' slug=post.slug %}">
                                                Devamını Oku... </a>
                                        </div>
                                    </div>
                                </div>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                    <!-- diger yazılar -->
                    <div class="row">
                        <div class="text-center"> <a class="button color1"
                                data-attr-shortcode="href:mesmerize_blog_link"
                                href="{%url 'yaratici:posts' %}">Diğer Yazılar</a></div>
                    </div>
                </div>
            </div>
            
            <div data-label="Bizi Takipte KALIN" data-id="cta--1" data-export-id="cta-blue-section-mc"
                data-category="cta"
                class="cta-blue-section-mc content-section content-section-spacing le_cocktail white-text"
                id="bizi-takipte-kalin"
                style="background-color: rgb(245, 250, 253); background-image: url(&quot;https://yaraticicocugum.com/anasayfa/wp-content/uploads/2020/10/Anasayfa_bos.jpg&quot;); background-size: cover; background-position: center top;">
                <div class="gridContainer">
                    <div class="row middle-xs">
                        <div class="col-sm-8 space-bottom-xs" data-type="column">
                            <h2 class="">Bizi Takipte Kalın!</h2>
                            <h6 class="">@yaratici_cocugum</h6>
                        </div>
                        <div class="col-sm-4 end-sm" data-type="column"> <a class="button blue"
                                href="https://www.instagram.com/yaratici_cocugum" target="_self" data-cp-link="1"
                                rel="noopener noreferrer">INSTAGRAM</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>



{%endblock %}

mysite/templates/yaratici/landing.html
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Yaratıcı Çocuğum - Çocuğunuzun Yaratıcı Enerjisine Dokunun!</title>
	<meta name="description"
		content="NLP Uzmanı Eğitimci Anneden, Çocuklarda Yaratıcılık Üzerine Paylaşımlar. Çocuklarımızla Düzenli Zaman Geçirip, Yaratıcılıklarını Artırlamayı Hedefliyoruz">
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-181247946-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());

		gtag('config', 'UA-181247946-1');
	</script>

	<link
		href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
		rel="stylesheet">

	<style>
		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
			font-family: 'Ubuntu', sans-serif;
			font-size: 40px;
		}

		body {
			background: rgb(255, 168, 162);
			background: linear-gradient(148deg, rgba(255, 168, 162, 1) 1%, rgba(115, 128, 198, 1) 39%);
		}

		.generalcontainer {
			margin: auto;

		}

		.text {
			position: absolute;
			top: 40%;
			left: 30%;
			color: #ffd1fc;
			margin-right: 20%;
			text-align: right;
		}

		img {
			float: right;
			min-height: 100px;
			max-height: 250px;
			opacity: 100%;
		}

		.logo {
			float: left;
		}

		img:hover {
			opacity: 80%;
			transition-duration: 0.3s;

		}
	</style>

</head>

<body>

	<div class="generalcontainer">
		<img class="logo" src="../../media/logo.png" alt="">
		<div class="text">
			<h1>Çocuğunuzun Yaratıcı Enerjisine</h1>
			<a href="{%url 'yaratici:home' %}">
				<img src="../../media/dokunun.png" alt="">
			</a>


		</div>

	</div>







</body>

</html>

mysite/templates/yaratici/question-results.html
{% extends './bootstrap.html'%}

{% block title %} {% endblock  %}
{% block meta %} {% endblock  %}

{% block css %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css'>
}
<style>
    @import url(https://fonts.googleapis.com/css?family=Roboto);

body {
    background-color: #f2f2f2;
    color: #000;
    font-family: 'Roboto', sans-serif;
}

.column-chart {
  position: relative;
  z-index: 20;
  bottom: 0;
  left: 50%;
  width: 100%;
  height: 320px;
  margin-top: 40px;
  margin-left: -50%;
}

@media (min-width: 568px) {
  .column-chart {
    width: 80%;
    margin-left: -40%;
  }
}

@media (min-width: 768px) {
  .column-chart {
    width: 60%;
    margin-left: -30%;
  }
}

@media (min-width: 992px) {
  .column-chart {
    width: 40%;
    margin-left: -20%;
  }
}

@media (min-width: 1024px) {
  .column-chart {
    width: 36%;
    margin-left: -18%;
  }
}

.column-chart:before,
.column-chart:after {
  position: absolute;
  content: '';
  top: 0;
  left: 0;
  width: calc(100% + 30px);
  height: 25%;
  margin-left: -15px;
  border-top: 1px dashed #b4b4b5;
  border-bottom: 1px dashed #b4b4b5;
}

.column-chart:after {
  top: 50%;
}

.column-chart > .legend {
  position: absolute;
  z-index: -1;
  top: 0;
}

.column-chart > .legend.legend-left {
  left: 0;
  width: 25px;
  height: 75%;
  margin-left: -55px;
  border: 1px solid #b4b4b5;
  border-right: none;
}

.column-chart > .legend.legend-left > .legend-title {
  display: block;
  position: absolute;
  top: 50%;
  left: 0;
  width: 65px;
  height: 50px;
  line-height: 50px;
  margin-top: -25px;
  margin-left: -60px;
  font-size: 28px;
  letter-spacing: 1px;
}

.column-chart > .legend.legend-right {
  right: 0;
  width: 100px;
  height: 100%;
  margin-right: -115px;
}

.column-chart > .legend.legend-right > .item {
  position: relative;
  width: 100%;
  height: 25%;
}

.column-chart > .legend.legend-right > .item > h4 {
  display: block;
  position: absolute;
  top: 0;
  right: 0;
  width: 100px;
  height: 40px;
  line-height: 40px;
  margin-top: -20px;
  font-size: 16px;
  text-align: right;
}

.column-chart > .chart {
  position: relative;
  z-index: 20;
  bottom: 0;
  left: 50%;
  width: 98%;
  height: 100%;
  margin-left: -49%;
}

.column-chart > .chart > .item {
  position: relative;
  float: left;
  height: 100%;
}

.column-chart > .chart > .item:before {
  position: absolute;
  z-index: -1;
  content: '';
  bottom: 0;
  left: 50%;
  width: 1px;
  height: calc(100% + 15px);
  border-right: 1px dashed #b4b4b5;
}

.column-chart > .chart > .item > .bar {
  position: absolute;
  bottom: 25px;
  left: 3px;
  width: 94%;
  height: 100%;
}

.column-chart > .chart > .item > .bar > span.percent {
  display: block;
  position: absolute;
  z-index: 25;
  bottom: -25px;
  left: 0;
  width: 100%;
  height: 26px;
  line-height: 26px;
  color: #fff;
  background-color: #3e50b4;
  font-size: 14px;
  font-weight: 700;
  text-align: center;
  letter-spacing: 1px;
}

.column-chart > .chart > .item > .bar > .item-progress {
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 20%;
  color: #fff;
  background-color: #ff4081;
}

.column-chart > .chart > .item > .bar > .item-progress > .title {
  <!-- position: absolute; -->
  top: calc(50% - 13px);
  left: 50%;
  font-size: 14px;
  text-align: center;
  <!-- text-transform: uppercase; -->
  letter-spacing: 0px;
  -moz-transform: translateX(-50%) translateY(-50%) rotate(-90deg);
  -webkit-transform: translateX(-50%) translateY(-50%) rotate(-90deg);
  transform: translateX(-50%) translateY(-50%) rotate(-90deg);
}

@media (min-width: 360px) {
  .column-chart > .chart > .item > .bar > .item-progress > .title {
    font-size: 16px;
  }
}

@media (min-width: 480px) {
  .column-chart > .chart > .item > .bar > .item-progress > .title {
    font-size: 18px;
  }
}
</style>

<style>
    .container {
        margin-top: 100px
    }
    
    .counter-box {
        display: block;
        background: #f6f6f6;
        padding: 40px 20px 37px;
        text-align: center
    }
    
    .counter-box p {
        margin: 5px 0 0;
        padding: 0;
        color: #909090;
        font-size: 18px;
        font-weight: 500
    }
    
    .counter-box i {
        font-size: 60px;
        margin: 0 0 15px;
        color: #d2d2d2
    }
    
    .counter {
        display: block;
        font-size: 32px;
        font-weight: 700;
        color: #666;
        line-height: 28px
    }
    
    .counter-box.colored {
        background: #3acf87
    }
    
    .counter-box.colored p,
    .counter-box.colored i,
    .counter-box.colored .counter {
        color: #fff
    }
</style>
{% endblock css %}


{%block content%}



<!-- pembe -->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="text-center text-uppercase">
                <h2>{{question.question}}</h2>
                <h3>Results</h3>
            </div>
            <!-- //.text-center -->

            <div class="column-chart">
                <div class="legend legend-left hidden-xs">
                    <h3 class="legend-title"></h3>
                </div>
                <!-- //.legend -->

                <div class="legend legend-right hidden-xs">
                    <div class="item">
                        <h4>%100</h4>
                    </div>
                    <!-- //.item -->

                    <div class="item">
                        <h4>%75</h4>
                    </div>
                    <!-- //.item -->

                    <div class="item">
                        <h4>%50</h4>
                    </div>
                    <!-- //.item -->

                    <div class="item">
                        <h4>%25</h4>
                    </div>
                    <!-- //.item -->
                </div>
                <!-- //.legend -->

                <div class="chart clearfix">

                    {% for choice in question.choices_set.all %}
                    <div class="item">
                        <div class="bar">
                            <span class="percent">{{choice.counter}}</span>
                            {% for key,value in dict.items %}
                            {% if key == choice.choice %}
                            <div class="item-progress" data-percent="{{value}}">
                                <span class="title">{{choice.choice}} %{{value}}</span>
                            </div>
                            {% endif %}
                            {%endfor%}
                            <!-- //.item-progress -->
                        </div>
                        <!-- //.bar -->
                    </div>
                    <!-- //.item -->
                    {%endfor%}


                </div>
                <!-- //.chart -->
            </div>
            <!-- //.column-chart -->
        </div>
        <!-- //.col-md-6 -->
    </div>
    <!-- //.row -->
</div>
<!-- //.pembe bitiş -->


<div class="container w-25 mt-5">
    {% for choice in question.choices_set.all %}

                            {% for key,value in dict.items %}
                            {% if key == choice.choice %}
                            <li class="list-group-item">
                                <span class='col-11'>{{choice.choice}}- %{{value}}</span>
                        
                            </li>
                            {% endif %}
                            {%endfor%}
                            {%endfor%}
    <a href="{% url 'yaratici:get_question' %}"><button type="submit" class="btn btn-primary mt-5">Go Back</button></a>
</div>

<script>
    $(document).ready(function(){
        columnChart();
        
        function columnChart(){
            var item = $('.chart', '.column-chart').find('.item'),
            itemWidth = 100 / item.length;
            item.css('width', itemWidth + '%');
            
            $('.column-chart').find('.item-progress').each(function(){
                var itemProgress = $(this),
                itemProgressHeight = $(this).parent().height() * ($(this).data('percent') / 100);
                itemProgress.css('height', itemProgressHeight);
            });
        };
    });
</script>




{%endblock%}